// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

// Command genui generates the SDUI ui authoring layer — the Go
// (ui/components.gen.go) and TypeScript (ts/ui.ts) ergonomic constructors — from
// the single authoring spec ui.spec.json, and lints that spec against the
// standard component definitions (definitions/*.json).
//
// The ui layer sits on a small hand-written runtime (ui/element.go,
// ts/ui_runtime.ts); this tool emits only the per-component constructors, the
// typed sugar, the slot helpers and the action/tone re-exports — the mechanical
// part — so adding a component is a spec edit, and Go/TS can never drift.
//
// Usage:
//
//	go run ./tools/genui         # regenerate the files, then lint
//	go run ./tools/genui -check  # verify the files are up to date (CI), then lint
//	go run ./tools/genui -lint   # lint the spec against definitions only
//
// Lint enforces coverage: every definition must have a component in the spec,
// every prop a definition's template binds must be exposed by some helper, and
// every Outlet a definition declares must have a slot helper. That is what makes
// the generator keep up — a new definition that nothing authors fails the build.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// ── spec model ───────────────────────────────────────────────────────────────

type spec struct {
	Tones      []tone      `json:"tones"`
	Actions    []action    `json:"actions"`
	Sugar      []sugar     `json:"sugar"`
	Slots      []slot      `json:"slots"`
	Components []component `json:"components"`
}

type tone struct {
	Const string `json:"const"`
	Sdui  string `json:"sdui"`
	Value string `json:"value"`
}

type arg struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Field string `json:"field"`
	Key   string `json:"key"`
}

type action struct {
	Func     string `json:"func"`
	Sdui     string `json:"sdui"`
	Kind     string `json:"kind"`
	Enum     string `json:"enum"`
	Doc      string `json:"doc"`
	Args     []arg  `json:"args"`
	Optional []arg  `json:"optional"`
}

type sugar struct {
	Func string `json:"func"`
	Key  string `json:"key"`
	Type string `json:"type"`
	Doc  string `json:"doc"`
}

type slot struct {
	Func string `json:"func"`
	Name string `json:"name"`
	Doc  string `json:"doc"`
}

type component struct {
	Func       string `json:"func"`
	Type       string `json:"type"`
	Doc        string `json:"doc"`
	Positional []arg  `json:"positional"`
	Variadic   *bool  `json:"variadic"`
	Generic    bool   `json:"generic"`
}

func (c component) variadic() bool { return c.Variadic == nil || *c.Variadic }

func main() {
	var (
		root  = "."
		check bool
		lint  bool
	)
	for _, a := range os.Args[1:] {
		switch a {
		case "-check":
			check = true
		case "-lint":
			lint = true
		default:
			if v, ok := strings.CutPrefix(a, "-root="); ok {
				root = v
			} else {
				fatalf("unknown argument %q", a)
			}
		}
	}

	sp := loadSpec(filepath.Join(root, "ui.spec.json"))

	goPath := filepath.Join(root, "ui", "components.gen.go")
	tsPath := filepath.Join(root, "ts", "ui.ts")
	goSrc := genGo(sp)
	tsSrc := genTS(sp)

	switch {
	case lint:
		// lint only
	case check:
		stale := false
		for _, f := range []struct {
			path string
			want []byte
		}{{goPath, goSrc}, {tsPath, tsSrc}} {
			got, err := os.ReadFile(f.path)
			if err != nil || !bytes.Equal(normalize(got), normalize(f.want)) {
				fmt.Fprintf(os.Stderr, "stale: %s (run `go run ./tools/genui`)\n", f.path)
				stale = true
			}
		}
		if stale {
			os.Exit(1)
		}
		fmt.Println("genui: generated files are up to date")
	default:
		writeFile(goPath, goSrc)
		writeFile(tsPath, tsSrc)
		fmt.Printf("genui: wrote %s and %s\n", goPath, tsPath)
	}

	if errs := runLint(sp, filepath.Join(root, "definitions")); len(errs) > 0 {
		for _, e := range errs {
			fmt.Fprintf(os.Stderr, "lint: %s\n", e)
		}
		os.Exit(1)
	}
	fmt.Println("genui: lint ok")
}

// ── Go generation ────────────────────────────────────────────────────────────

func genGo(sp spec) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.\n")
	b.WriteString("// SPDX-License-Identifier: Apache-2.0\n")
	b.WriteString("// SPDX-FileCopyrightText: 2026 the Mosaic authors\n\n")
	b.WriteString("package ui\n\n")
	if len(sp.Tones) > 0 || len(sp.Actions) > 0 {
		b.WriteString("import \"github.com/mosaic-media/contracts/sdui\"\n\n")
	}

	b.WriteString("// ── components ─────────────────────────────────────────────────────────────\n\n")
	for _, c := range sp.Components {
		if c.Doc != "" {
			fmt.Fprintf(&b, "// %s %s\n", c.Func, dropLeadName(c.Func, c.Doc))
		}
		params := []string{}
		if c.Generic {
			params = append(params, "typ string")
		}
		for _, p := range c.Positional {
			params = append(params, p.Name+" "+goType(p.Type))
		}
		if c.variadic() {
			params = append(params, "els ...El")
		}
		typExpr := strconv.Quote(c.Type)
		if c.Generic {
			typExpr = "typ"
		}
		elsArg := "nil"
		if c.variadic() {
			elsArg = "els"
		}
		fmt.Fprintf(&b, "func %s(%s) *Element { return compose(%s, %s, %s) }\n\n",
			c.Func, strings.Join(params, ", "), typExpr, goBase(c.Positional), elsArg)
	}

	b.WriteString("// ── slots ──────────────────────────────────────────────────────────────────\n\n")
	for _, s := range sp.Slots {
		if s.Doc != "" {
			fmt.Fprintf(&b, "// %s %s\n", s.Func, dropLeadName(s.Func, s.Doc))
		}
		fmt.Fprintf(&b, "func %s(els ...El) El { return Slot(%s, els...) }\n\n", s.Func, strconv.Quote(s.Name))
	}

	b.WriteString("// ── sugar ──────────────────────────────────────────────────────────────────\n\n")
	for _, s := range sp.Sugar {
		if s.Doc != "" {
			fmt.Fprintf(&b, "// %s %s\n", s.Func, dropLeadName(s.Func, s.Doc))
		}
		fmt.Fprintf(&b, "func %s(%s) El { return Prop(%s, v) }\n\n", s.Func, goSugarParam(s.Type), strconv.Quote(s.Key))
	}

	if len(sp.Tones) > 0 {
		b.WriteString("// Tone values (the open-bag string encoding), re-exported from the producer binding.\n")
		b.WriteString("const (\n")
		for _, t := range sp.Tones {
			fmt.Fprintf(&b, "\t%s = sdui.%s\n", t.Const, t.Sdui)
		}
		b.WriteString(")\n\n")
	}

	if len(sp.Actions) > 0 {
		b.WriteString("// Action constructors, re-exported from the producer binding; they ride the open\n")
		b.WriteString("// props bag as JSON (ADR 0044).\n")
		b.WriteString("var (\n")
		for _, a := range sp.Actions {
			fmt.Fprintf(&b, "\t%s = sdui.%s\n", a.Func, a.Sdui)
		}
		b.WriteString(")\n")
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, b.String())
		fatalf("gofmt generated Go: %v", err)
	}
	return out
}

func goType(t string) string {
	switch t {
	case "string":
		return "string"
	case "int":
		return "int"
	case "number":
		return "float64"
	case "Action":
		return "Action"
	case "props":
		return "map[string]any"
	default:
		fatalf("unknown Go type %q", t)
		return ""
	}
}

// goSugarParam renders the single value parameter of a sugar helper, variadic
// for list types.
func goSugarParam(t string) string {
	if t == "[]string" {
		return "v ...string"
	}
	return "v " + goType(t)
}

func goBase(pos []arg) string {
	if len(pos) == 0 {
		return "nil"
	}
	parts := make([]string, len(pos))
	for i, p := range pos {
		parts[i] = fmt.Sprintf("%s: %s", strconv.Quote(p.Key), p.Name)
	}
	return "map[string]any{" + strings.Join(parts, ", ") + "}"
}

// ── TypeScript generation ────────────────────────────────────────────────────

func genTS(sp spec) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.\n")
	b.WriteString("// SPDX-License-Identifier: Apache-2.0\n")
	b.WriteString("// SPDX-FileCopyrightText: 2026 the Mosaic authors\n\n")
	b.WriteString("import { ActionKind, type Action } from \"./contract.gen.js\";\n")
	b.WriteString("import { compose, Prop, Slot, type El, type Elish, type Element, type Props } from \"./ui_runtime.js\";\n\n")
	b.WriteString("export { Group, ID, Prop, Slot, When, Element } from \"./ui_runtime.js\";\n")
	b.WriteString("export type { El, Elish, Props } from \"./ui_runtime.js\";\n")
	b.WriteString("export { ActionKind, Surface, Tone } from \"./contract.gen.js\";\n")
	b.WriteString("export type { Action, UINode } from \"./contract.gen.js\";\n\n")

	b.WriteString("// ── components ─────────────────────────────────────────────────────────────\n\n")
	for _, c := range sp.Components {
		if c.Doc != "" {
			fmt.Fprintf(&b, "/** %s */\n", c.Doc)
		}
		params := []string{}
		if c.Generic {
			params = append(params, "typ: string")
		}
		for _, p := range c.Positional {
			params = append(params, p.Name+": "+tsType(p.Type))
		}
		if c.variadic() {
			params = append(params, "...els: Elish[]")
		}
		typExpr := strconv.Quote(c.Type)
		if c.Generic {
			typExpr = "typ"
		}
		elsArg := "[]"
		if c.variadic() {
			elsArg = "els"
		}
		fmt.Fprintf(&b, "export function %s(%s): Element {\n  return compose(%s, %s, %s);\n}\n\n",
			c.Func, strings.Join(params, ", "), typExpr, tsBase(c.Positional), elsArg)
	}

	b.WriteString("// ── slots ──────────────────────────────────────────────────────────────────\n\n")
	for _, s := range sp.Slots {
		if s.Doc != "" {
			fmt.Fprintf(&b, "/** %s */\n", s.Doc)
		}
		fmt.Fprintf(&b, "export function %s(...els: Elish[]): El {\n  return Slot(%s, ...els);\n}\n\n", s.Func, strconv.Quote(s.Name))
	}

	b.WriteString("// ── sugar ──────────────────────────────────────────────────────────────────\n\n")
	for _, s := range sp.Sugar {
		if s.Doc != "" {
			fmt.Fprintf(&b, "/** %s */\n", s.Doc)
		}
		fmt.Fprintf(&b, "export function %s(%s): El {\n  return Prop(%s, v);\n}\n\n", s.Func, tsSugarParam(s.Type), strconv.Quote(s.Key))
	}

	if len(sp.Tones) > 0 {
		b.WriteString("// Tone values (the open-bag string encoding), mirroring the Go Tone constants.\n")
		for _, t := range sp.Tones {
			fmt.Fprintf(&b, "export const %s = %s as const;\n", t.Const, strconv.Quote(t.Value))
		}
		b.WriteString("\n")
	}

	if len(sp.Actions) > 0 {
		b.WriteString("// ── actions ────────────────────────────────────────────────────────────────\n")
		b.WriteString("// Actions ride inside the open props bag as JSON (ADR 0044); each constructor\n")
		b.WriteString("// hides the discriminator and the optional fields.\n\n")
		for _, a := range sp.Actions {
			if a.Doc != "" {
				fmt.Fprintf(&b, "/** %s */\n", a.Doc)
			}
			params := make([]string, 0, len(a.Args)+len(a.Optional))
			for _, ar := range a.Args {
				params = append(params, ar.Name+": "+tsType(ar.Type))
			}
			for _, op := range a.Optional {
				params = append(params, op.Name+"?: "+tsType(op.Type))
			}
			fields := make([]string, 0, len(a.Args)+1)
			fields = append(fields, "kind: ActionKind."+a.Enum)
			for _, ar := range a.Args {
				fields = append(fields, tsField(ar.Field, ar.Name))
			}
			body := "{ " + strings.Join(fields, ", ")
			for _, op := range a.Optional {
				body += fmt.Sprintf(", ...(%s ? { %s } : {})", op.Name, tsField(op.Field, op.Name))
			}
			body += " }"
			fmt.Fprintf(&b, "export function %s(%s): Action {\n  return %s;\n}\n\n", a.Func, strings.Join(params, ", "), body)
		}
	}

	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}

func tsType(t string) string {
	switch t {
	case "string":
		return "string"
	case "int", "number":
		return "number"
	case "Action":
		return "Action"
	case "props":
		return "Props"
	default:
		fatalf("unknown TS type %q", t)
		return ""
	}
}

func tsSugarParam(t string) string {
	if t == "[]string" {
		return "...v: string[]"
	}
	return "v: " + tsType(t)
}

func tsBase(pos []arg) string {
	if len(pos) == 0 {
		return "undefined"
	}
	parts := make([]string, len(pos))
	for i, p := range pos {
		parts[i] = tsField(p.Key, p.Name)
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

// tsField renders an object entry, using shorthand when the key equals the name.
func tsField(key, name string) string {
	if key == name {
		return name
	}
	return strconv.Quote(key) + ": " + name
}

// ── lint ─────────────────────────────────────────────────────────────────────

func runLint(sp spec, defsDir string) []string {
	var errs []string

	// Integrity: no duplicate exported names.
	seen := map[string]string{}
	claim := func(name, kind string) {
		if prev, ok := seen[name]; ok {
			errs = append(errs, fmt.Sprintf("duplicate name %q (%s and %s)", name, prev, kind))
		}
		seen[name] = kind
	}
	for _, c := range sp.Components {
		claim(c.Func, "component")
	}
	for _, s := range sp.Slots {
		claim(s.Func, "slot")
	}
	for _, s := range sp.Sugar {
		claim(s.Func, "sugar")
	}
	for _, a := range sp.Actions {
		claim(a.Func, "action")
	}
	for _, t := range sp.Tones {
		claim(t.Const, "tone")
	}

	// Authorable prop keys: any positional key across components, plus every
	// sugar key. A definition may bind any of these.
	authorable := map[string]bool{}
	for _, c := range sp.Components {
		for _, p := range c.Positional {
			authorable[p.Key] = true
		}
	}
	for _, s := range sp.Sugar {
		authorable[s.Key] = true
	}
	slotNames := map[string]bool{}
	for _, s := range sp.Slots {
		slotNames[s.Name] = true
	}
	byType := map[string]bool{}
	for _, c := range sp.Components {
		if c.Type != "" {
			byType[c.Type] = true
		}
	}

	files, _ := filepath.Glob(filepath.Join(defsDir, "*.json"))
	sort.Strings(files)
	for _, f := range files {
		raw, err := os.ReadFile(f)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: %v", f, err))
			continue
		}
		var def struct {
			Name     string `json:"name"`
			Template any    `json:"template"`
		}
		if err := json.Unmarshal(raw, &def); err != nil {
			errs = append(errs, fmt.Sprintf("%s: %v", f, err))
			continue
		}
		base := filepath.Base(f)
		if !byType[def.Name] {
			errs = append(errs, fmt.Sprintf("%s: definition %q has no component in ui.spec.json — add one (a new component needs an authoring entry)", base, def.Name))
			continue
		}
		binds, aliases, outlets := map[string]bool{}, map[string]bool{}, map[string]bool{}
		collect(def.Template, binds, aliases, outlets)
		for b := range binds {
			if aliases[b] {
				continue // a local $each alias, not a component prop
			}
			if !authorable[b] {
				errs = append(errs, fmt.Sprintf("%s: template binds %q but no ui helper sets it (add it as a positional arg or sugar in ui.spec.json)", base, b))
			}
		}
		for o := range outlets {
			if !slotNames[o] {
				errs = append(errs, fmt.Sprintf("%s: template declares Outlet %q but no slot helper fills it", base, o))
			}
		}
	}

	sort.Strings(errs)
	return errs
}

// collect walks a definition template gathering $bind prop paths, $as loop
// aliases, and Outlet slot names.
func collect(v any, binds, aliases, outlets map[string]bool) {
	switch x := v.(type) {
	case map[string]any:
		if b, ok := x["$bind"].(string); ok {
			binds[b] = true
		}
		if a, ok := x["$as"].(string); ok {
			aliases[a] = true
		}
		if t, ok := x["type"].(string); ok && t == "Outlet" {
			if props, ok := x["props"].(map[string]any); ok {
				if name, ok := props["name"].(string); ok {
					outlets[name] = true
				}
			}
		}
		for _, val := range x {
			collect(val, binds, aliases, outlets)
		}
	case []any:
		for _, val := range x {
			collect(val, binds, aliases, outlets)
		}
	}
}

// ── helpers ──────────────────────────────────────────────────────────────────

func loadSpec(path string) spec {
	raw, err := os.ReadFile(path)
	if err != nil {
		fatalf("read spec: %v", err)
	}
	var sp spec
	if err := json.Unmarshal(raw, &sp); err != nil {
		fatalf("parse spec: %v", err)
	}
	return sp
}

func writeFile(path string, data []byte) {
	if err := os.WriteFile(path, data, 0o644); err != nil {
		fatalf("write %s: %v", path, err)
	}
}

// dropLeadName lets a spec doc read as a full sentence in prose while GoDoc gets
// the required "Name …" lead: if the doc already starts with the func name, the
// name is not duplicated.
func dropLeadName(name, doc string) string {
	if rest, ok := strings.CutPrefix(doc, name+" "); ok {
		return rest
	}
	return doc
}

// normalize makes byte comparison newline-insensitive so a CRLF checkout does
// not read as stale against LF-generated output.
func normalize(b []byte) []byte {
	return bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
}

func fatalf(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "genui: "+format+"\n", a...)
	os.Exit(1)
}
