// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

// Package mosaic.auth.v1 is how a client obtains the session every other
// first-party call needs (ADR 0061).
//
// It is deliberately a service of its own rather than more RPCs on
// mosaic.session.v1.SessionService. Every request on that service begins with a
// session ref, because a session intent is by definition something a session
// does; sign-in is the one call made *without* a session, and folding it in
// would put the service's only unauthenticated methods next to the ones whose
// whole contract is that they are authenticated. Separating them also lets the
// Platform mount them behind different interceptors.
//
// This surface replaced the GraphQL signIn/signOut mutations when ADR 0061
// retired the GraphQL transport. Errors carry the Platform's fixed error
// categories as Connect/gRPC codes — a bad password is UNAUTHENTICATED, not a
// 200 with an error object.

// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=none"
// @generated from file mosaic/auth/v1/auth.proto (package mosaic.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mosaic/auth/v1/auth.proto.
 */
export const file_mosaic_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("Chltb3NhaWMvYXV0aC92MS9hdXRoLnByb3RvEg5tb3NhaWMuYXV0aC52MSJGCg1TaWduSW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhEKCWRldmljZV9pZBgDIAEoCSI6Cg5TaWduSW5SZXNwb25zZRIoCgdzZXNzaW9uGAEgASgLMhcubW9zYWljLmF1dGgudjEuU2Vzc2lvbiJACg5TaWduT3V0UmVxdWVzdBIWCg5jYWxsZXJfc2Vzc2lvbhgBIAEoCRIWCg50YXJnZXRfc2Vzc2lvbhgCIAEoCSIiCg9TaWduT3V0UmVzcG9uc2USDwoHc2Vzc2lvbhgBIAEoCSLhAQoHU2Vzc2lvbhIKCgJpZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhEKCWRldmljZV9pZBgDIAEoCRItCglpc3N1ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDGxhc3Rfc2Vlbl9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZXhwaXJlc19hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFQoNYXV0aF9zdHJlbmd0aBgHIAEoCTKiAQoLQXV0aFNlcnZpY2USRwoGU2lnbkluEh0ubW9zYWljLmF1dGgudjEuU2lnbkluUmVxdWVzdBoeLm1vc2FpYy5hdXRoLnYxLlNpZ25JblJlc3BvbnNlEkoKB1NpZ25PdXQSHi5tb3NhaWMuYXV0aC52MS5TaWduT3V0UmVxdWVzdBofLm1vc2FpYy5hdXRoLnYxLlNpZ25PdXRSZXNwb25zZUI9WjtnaXRodWIuY29tL21vc2FpYy1tZWRpYS9jb250cmFjdHMvZ2VuL21vc2FpYy9hdXRoL3YxO2F1dGh2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * SignInRequest is a local username/password authentication from a named
 * device. device_id is required: a session belongs to a device, so the Platform
 * can revoke one client without ending the others.
 *
 * @generated from message mosaic.auth.v1.SignInRequest
 */
export type SignInRequest = Message<"mosaic.auth.v1.SignInRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string device_id = 3;
   */
  deviceId: string;
};

/**
 * Describes the message mosaic.auth.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema: GenMessage<SignInRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_auth_v1_auth, 0);

/**
 * SignInResponse carries the issued session.
 *
 * @generated from message mosaic.auth.v1.SignInResponse
 */
export type SignInResponse = Message<"mosaic.auth.v1.SignInResponse"> & {
  /**
   * @generated from field: mosaic.auth.v1.Session session = 1;
   */
  session?: Session | undefined;
};

/**
 * Describes the message mosaic.auth.v1.SignInResponse.
 * Use `create(SignInResponseSchema)` to create a new message.
 */
export const SignInResponseSchema: GenMessage<SignInResponse> = /*@__PURE__*/
  messageDesc(file_mosaic_auth_v1_auth, 1);

/**
 * SignOutRequest revokes target_session on behalf of caller_session.
 *
 * @generated from message mosaic.auth.v1.SignOutRequest
 */
export type SignOutRequest = Message<"mosaic.auth.v1.SignOutRequest"> & {
  /**
   * @generated from field: string caller_session = 1;
   */
  callerSession: string;

  /**
   * @generated from field: string target_session = 2;
   */
  targetSession: string;
};

/**
 * Describes the message mosaic.auth.v1.SignOutRequest.
 * Use `create(SignOutRequestSchema)` to create a new message.
 */
export const SignOutRequestSchema: GenMessage<SignOutRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_auth_v1_auth, 2);

/**
 * SignOutResponse echoes the session that was revoked.
 *
 * @generated from message mosaic.auth.v1.SignOutResponse
 */
export type SignOutResponse = Message<"mosaic.auth.v1.SignOutResponse"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;
};

/**
 * Describes the message mosaic.auth.v1.SignOutResponse.
 * Use `create(SignOutResponseSchema)` to create a new message.
 */
export const SignOutResponseSchema: GenMessage<SignOutResponse> = /*@__PURE__*/
  messageDesc(file_mosaic_auth_v1_auth, 3);

/**
 * Session is the projection of an issued session a client is allowed to see.
 *
 * There is deliberately no capabilities field. domain.Session models one and
 * the Postgres store round-trips it, but nothing populates it at issue time, so
 * the GraphQL surface this replaced returned an empty list on every sign-in. A
 * contract that always sends an empty list is worse than one that does not
 * mention it: a client would reasonably read "no capabilities" as "hide
 * everything". Capability-gated affordances (ADR 0036) therefore stay a server
 * concern — the Platform omits what the caller cannot use when it renders the
 * screen. Add the field when a session genuinely carries the set, and it is a
 * backward-compatible addition when that happens.
 *
 * @generated from message mosaic.auth.v1.Session
 */
export type Session = Message<"mosaic.auth.v1.Session"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string device_id = 3;
   */
  deviceId: string;

  /**
   * @generated from field: google.protobuf.Timestamp issued_at = 4;
   */
  issuedAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp last_seen_at = 5;
   */
  lastSeenAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 6;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: string auth_strength = 7;
   */
  authStrength: string;
};

/**
 * Describes the message mosaic.auth.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema: GenMessage<Session> = /*@__PURE__*/
  messageDesc(file_mosaic_auth_v1_auth, 4);

/**
 * AuthService mints and revokes sessions. Both calls are unary: there is
 * nothing to push before a client has a session to push to.
 *
 * @generated from service mosaic.auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * SignIn authenticates a local user with a password and issues a session.
   * The returned session id is the opaque ref (ADR 0017) the client presents on
   * every SessionService call.
   *
   * @generated from rpc mosaic.auth.v1.AuthService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof SignInResponseSchema;
  },
  /**
   * SignOut revokes a session server-side. A client revoking its own session
   * passes the same value for both fields; revoking another device's session is
   * an authorised act, which is why the caller is named separately.
   *
   * @generated from rpc mosaic.auth.v1.AuthService.SignOut
   */
  signOut: {
    methodKind: "unary";
    input: typeof SignOutRequestSchema;
    output: typeof SignOutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_mosaic_auth_v1_auth, 0);

